# Setup
title:               Minias
tagline:             "Minias blog's"
description:         'Share tips and knowledge.'
url:                 https://gnuhacker.com
baseurl:             ''
paginate:            20
permalink:           pretty
highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# About/contact
author:
  name:              Minias
  url:               https://gnuhacker.com
  email:             gnuhacker@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
heme: jekyll-theme-tactile

exclude: [changelog.md,SECURITY.md, LICENSE.md, README.md, Gemfile, Gemfile.lock]
