# Setup
title:               Minias
tagline:             "Tech blog's"
description:         'Share tips and knowledge.'
url:                 https://gnuhacker.com
baseurl:             ''
paginate:            20
permalink:           pretty
markdown: kramdown

# About/contact
author:
  name:              Minias
  url:               https://gnuhacker.com
  email:             gnuhacker@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

heme: jekyll-theme-tactile
