# Setup
title:               Minias
tagline:             'tagline'
description:         'description'
url:                 https://tdiads.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Minias
  url:               https://minias.github.io.com
  email:             admin@gnuhacker.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

theme: jekyll-theme-tactile
