# Setup
title:               Minias
tagline:             "Minias blog's"
description:         'Share tips and knowledge.'
url:                 https://minias.github.io
baseurl:             ''
paginate:            20
permalink:           pretty
markdown: kramdown

# About/contact
author:
  name:              Minias
  url:               https://minias.github.io
  email:             gnuhacker@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0 
heme: jekyll-theme-tactile
