# Setup
title:               TDI ADS
tagline:             '기술 블로그'
description:         'TDI ADS의 기술블로그입니다.'
url:                 https://tdiads.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              TDIADS
  url:               https://tdiads.com
  email:             tdi9@tdi9.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

theme: jekyll-theme-tactile
